name: PHP CI

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1', '8.2']

    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v3
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml
      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist
      - name: Run Pest Tests
        run: vendor/bin/pest --colors
